version: '3.3'

services:
  api:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    container_name: app_api
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:7.0
    volumes:
      - redisdata:/data

volumes:
  redisdata: